/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Message } from "./Message";
export * as factories from "./factories";
export { Message__factory } from "./factories/Message__factory";
